services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 5173:80
    restart: always

  web:
    ports:
      - 80:80
    restart: always

  backend:
    restart: always
