services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: >
      /bin/sh -c "envsubst '\$${FLASK_SERVER_ADDR}' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    env_file:
      - .env
    volumes:
      - ./flask:/src
    ports:
      - "9091:9091"
      
  frontend-builder:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - /app/node_modules
    command: sh -c "npm install && npm run build"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 5173:80

  